### ISSUE TITLE
Identifying the cause of require-final-newline warning

### ISSUE THREAD

**Issue by expez** [glasserc/ethan-wspace#28] opened 2015-12-14 10:43 UTC
For the last year or so I've been getting 

```
Warning (:warning): You have
`require-final-newline' turned on.  ethan-wspace supersedes
`require-final-newline', and so `require-final-newline' will be
turned off.  If you turned on `require-final-newline' in your
customizations, you can disable this warning by removing these
customizations.  Otherwise, please file a bug report, as some
other code has turned on `require-final-newline'.
```

When I grep through the `.emacs.d` folder (including everything installed under `emacs.d/elpa`) I get 0 hits.  How on earth can I get rid of this annoying warning?  Does ethan-wspace know who the culprit is?  If so, it would be super helpful if it gave some indication about where to look.

**Comment by glasserc** [comment] 2015-12-14 14:13
No, it's not really possible to write code that checks in emacs-lisp "who set this variable to this value". In the past it's tended to be built-in emacs modes -- e.g. https://github.com/glasserc/ethan-wspace/issues/25 demonstrates when it was python-mode. But I think that got fixed in 24.4 or so. What emacs version are you running? Do you notice this warning most in certain modes? Do you have `mode-require-final-newline` turned on?

**Comment by expez** [comment] 2015-12-14 14:26
>  Do you have mode-require-final-newline turned on?

nope

**Comment by glasserc** [comment] 2015-12-15 02:51
What emacs version are you running? When you start `emacs -q`, is `require-final-newline` set?

**Comment by expez** [comment] 2015-12-15 08:55
> What emacs version are you running?

24.5.1

> When you start `emacs -q`, is `require-final-newline` set?

No

**Comment by glasserc** [comment] 2015-12-15 15:54
What files/buffers/modes do you get the warning in?

Is there a way for me to run your emacs configuration to try to reproduce it?

What ELPA packages do you have installed?

**Comment by expez** [comment] 2015-12-16 08:13
> What files/buffers/modes do you get the warning in?

I get the warning in a buffer called `*warnings*`.

> Is there a way for me to run your emacs configuration to try to reproduce it?

https://github.com/expez/.emacs.d

> What ELPA packages do you have installed?

All of them...

**Comment by glasserc** [comment] 2015-12-18 02:09
Downloading and running your .emacs.d seems to reproduce it, as does running `emacs -q`. I believe `require-final-newline` is being set because `mode-require-final-newline` is `t`, and I believe that is because `t` is the default. There is a warning in `ethan-wspace` about `mode-require-final-newline` as well as `require-final-newline`, but I think it isn't working as designed. Either way, I decided to update the documentation to make it a little clearer from a casual glance that you'll need to disable `mode-require-final-newline`, which I hadn't realized was a default.

**Comment by expez** [comment] 2015-12-18 14:54
Thanks for taking a look, I already have `mode-require-final-newline` set to `nil`, though:

https://github.com/expez/.emacs.d/blob/master/lisp/init-whitespace.el#L11-L12

**Comment by glasserc** [comment] 2015-12-19 19:29
I'm sorry! When trying to load your .emacs.d, I encountered a bunch of errors that I hadn't noticed because they were in an `*init-errors*` buffer. I think I have it loading "enough" right now to see the errors. Yes, it looks like you're setting the variables correctly. I did a grep on the files installed by elpa and I noticed that `bookmark+` and `auctex` both set `require-final-newline` unconditionally to `t`. Can you try disabling `bookmark+`? That's my suspicion. I'll try to look at this more but it won't be until tomorrow.

If `bookmark+` is the culprit, then your options might be to 1) request upstream `bookmark+` to not set `require-final-newline` unconditionally, but only to copy the value of `mode-require-final-newline`, or 2) somehow disable `ethan-wspace` from running on whatever files `bookmark+` is managing. This might be necessary if the final newlines are necessary to the operation of `bookmark+`.

**Comment by expez** [comment] 2015-12-20 09:48
Hi

You're really going above and beyond here and I really appreciate it!

I commented out the package-require call for auctex (I use this so rarely so that's no biggie) and got rid of bookmark+ which I've forgotten about and not used in the last year :p But!  The problem still remains :( 

I even deleted the folders in `.emacs.d/elpa` in case the leftovers still got loaded.

**Comment by glasserc** [comment] 2015-12-21 02:41
OK, so I think I figured out what's going on here. I'll relate the whole war story, with the TL;DR at the end.

While I was poking I also happened to notice that anaphora.el has a file-local variable of `require-final-newline: t`, but I don't think that's doing anything (it should only be used when the file is loaded using e.g. `find-file`). Also, I noticed that `dired+` requires `bookmark+.el`, but I have no idea what triggers the `require-final-newline` in `bookmark+` so I am equally in the dark about what might trigger it in `dired+`. But I think it ends up not being related.

I fell back on the old standby of binary-searching all your code by deleting a bunch of files from `lisp/init-*.el` and restarting emacs, and then repeating. The first thing I noticed was that at first, I had five copies of the `require-final-newline` warning, but as I deleted files, that number of warnings dropped to 2 and then to 1, and then 0 when I deleted `init-misc.el`. Restoring `init-misc.el` from git brought the warning back; deleting it made it go away. At first I figured this must mean that several somethings were triggering the warning, but I decided to start on the `init-misc.el` one first. I commented out code and restarted emacs, etc. until I tracked it down to the call to turn on `workgroups-mode`. I've never used `workgroups-mode`, but I guess it's responsible for keeping track of what buffers are open and re-opening them when you restart emacs? I tried probing the definition of `workgroups-mode` but didn't see anything suspicious. Eventually I wondered if `workgroups-mode` was re-opening the `*Warnings*` buffer, so I rm'd the ~/.emacs.d/workgroups file and restarted emacs... and the warnings went away!

But then I couldn't figure out how to bring them back. I ended up restoring all the files I deleted and I still didn't have any warnings. Eventually I realized that the old workgroup had a file open in it (`init-whitespace.el`). So I tried opening that file, closing and re-opening emacs, and: boom, one warning.

So what I think is going on is that `init-misc.el` is getting run before `init-whitespace.el`, so when you start `workgroups-mode.el`, it reopens all your outstanding files with `mode-require-final-newline` still having the default value of `t`, so all these files end up with `require-final-newline` turned on. Then, when you load `init-whitespace.el`, it turns off `mode-require-final-newline`, and then starts `ethan-wspace` in all the open buffers, which all have `require-final-newline` turned on. The end result is that `ethan-wspace` doesn't warn about `mode-require-final-newline`, which is already off by the time it's running, but warns once for each open buffer. I guess deleted files don't get opened, which is why the number of warnings went down as I deleted files. All of this is quite a pain to track, but I think unavoidable given that emacs's state is almost entirely global variables.

If my theory is correct, you should be able to work around this by either setting `mode-require-final-newline` to `nil` before you start up `workgroups-mode`, or by changing the order that `init-whitespace` and `init-misc` get loaded (I renamed `init-misc` to `init-wmisc`). Both seemed to work in my experiments, but I'm still taking on faith that I'm seeing exactly the same behavior you are rather than just some other misbehavior. Could you try one of those and let me know how it goes? Hope this helps!

**Comment by expez** [comment] 2015-12-21 09:03
I moved the setting of `require-final-newline` all the way to the start of the loading process and that did it!  Thank you so much for all your work on this!

**Closed** 2015-12-21 09:03 UTC
